import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        navy: "#2d3a8c",
        teal: { DEFAULT: "#2a8c78", light: "#3db99a" },
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        chart: {
          "1": "var(--chart-1)",
          "2": "var(--chart-2)",
          "3": "var(--chart-3)",
          "4": "var(--chart-4)",
          "5": "var(--chart-5)",
        },
        sidebar: {
          DEFAULT: "var(--sidebar-background)",
          foreground: "var(--sidebar-foreground)",
          primary: "var(--sidebar-primary)",
          "primary-foreground": "var(--sidebar-primary-foreground)",
          accent: "var(--sidebar-accent)",
          "accent-foreground": "var(--sidebar-accent-foreground)",
          border: "var(--sidebar-border)",
          ring: "var(--sidebar-ring)",
        },
        /* MD3 surface palette — used by camera/immersive screens */
        "md-surface":                    "var(--md-surface)",
        "md-surface-container":          "var(--md-surface-container)",
        "md-surface-container-low":      "var(--md-surface-container-low)",
        "md-surface-container-high":     "var(--md-surface-container-high)",
        "md-surface-container-highest":  "var(--md-surface-container-highest)",
        "md-surface-bright":             "var(--md-surface-bright)",
        "md-on-surface":                 "var(--md-on-surface)",
        "md-on-surface-variant":         "var(--md-on-surface-variant)",
        "md-outline":                    "var(--md-outline)",
        "md-outline-variant":            "var(--md-outline-variant)",
        "md-primary":                    "var(--md-primary)",
        "md-primary-dim":                "var(--md-primary-dim)",
        "md-secondary":                  "var(--md-secondary)",
        "md-tertiary":                   "var(--md-tertiary)",
        "md-tertiary-fixed":             "var(--md-tertiary-fixed)",
        "md-error":                      "var(--md-error)",
        "scanner-accent": "hsl(var(--scanner-accent))",
        sheet: {
          bg: "hsl(var(--sheet-bg))",
          border: "hsl(var(--sheet-border))",
          text: "hsl(var(--sheet-text))",
          muted: "hsl(var(--sheet-text-muted))",
          card: "hsl(var(--sheet-card-bg))",
          selected: "hsl(var(--sheet-card-selected))",
          "selected-border": "hsl(var(--sheet-card-border-selected))",
        },
        "highlight-green": "var(--highlight-green)",
        "highlight-blue":  "var(--highlight-blue)",
        "highlight-pink":  "var(--highlight-pink)",
        "queue-glow":      "var(--queue-glow)",
      },
      fontFamily: {
        sans:     ["var(--font-sans)"],
        serif:    ["var(--font-serif)"],
        mono:     ["var(--font-mono)"],
        headline: ["Manrope", "system-ui", "sans-serif"],
        body:     ["Inter", "system-ui", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to:   { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to:   { height: "0" },
        },
        scanLine: {
          "0%":   { top: "4px",   opacity: "0" },
          "10%":  { opacity: "1" },
          "90%":  { opacity: "1" },
          "100%": { top: "212px", opacity: "0" },
        },
        scanPulse: {
          "0%, 100%": { transform: "scale(0.95)", opacity: "0.6" },
          "50%":      { transform: "scale(1.02)", opacity: "1" },
        },
        sheetSlideUp: {
          from: { transform: "translateY(100%)" },
          to:   { transform: "translateY(0)" },
        },
        slideUp: {
          from: { transform: "translateY(12px)", opacity: "0" },
          to:   { transform: "translateY(0)",    opacity: "1" },
        },
        stepPulse: {
          "0%, 100%": { opacity: "1" },
          "50%":      { opacity: "0.4" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        scanLine:         "scanLine 2s ease-in-out infinite",
        scanPulse:        "scanPulse 1.8s ease-out infinite",
        "scan-pulse":     "scanPulse 1.8s ease-out infinite",
        "label-in":       "labelFadeIn 250ms ease-out forwards",
        "border-glow":    "borderGlow 1.5s ease-in-out infinite",
        "sheet-up":       "sheetSlideUp 320ms cubic-bezier(0.22,1,0.36,1) forwards",
        "slide-up":       "slideUp 300ms ease-out",
        stepPulse:        "stepPulse 1s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
